# .streamlit/config.toml

# Este será el tema oscuro que se cargará por defecto al iniciar la aplicación.
# El interruptor que creamos en la app se encargará de cambiarlo dinámicamente.
[theme]
primaryColor="#46b1e2"
backgroundColor="#080f1a"
secondaryBackgroundColor="#192e3f"
textColor="#d9dddf"
font="sans serif"